from io import BytesIO
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fpdf import FPDF

def sanitize_text(text):
    for a,b in {"“":'"',"”":'"',"‘":"'","’":"'","–":"-","—":"-","•":"-"}.items():
        text=text.replace(a,b)
    return text

def format_docx(text, doc_type):
    doc=Document()
    sec=doc.sections[0]
    sec.top_margin=Inches(.7); sec.bottom_margin=Inches(.7); sec.left_margin=Inches(.8); sec.right_margin=Inches(.8)
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    r=p.add_run(sanitize_text(doc_type).upper()); r.bold=True; r.font.name="Times New Roman"; r.font.size=Pt(16)
    for line in sanitize_text(text).splitlines():
        line=line.strip()
        if not line: doc.add_paragraph(); continue
        p=doc.add_paragraph()
        r=p.add_run(line)
        if (line.isupper() and len(line)<100) or line.endswith(":"): r.bold=True
        r.font.name="Times New Roman"; r.font.size=Pt(11)
    footer=sec.footer.paragraphs[0]; footer.alignment=WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run("Generated by LegalEase - Draft for review").font.size=Pt(9)
    out=BytesIO(); doc.save(out); return out.getvalue()

class LegalPDF(FPDF):
    def footer(self):
        self.set_y(-15); self.set_font("Helvetica",size=8)
        self.cell(0,10,"Generated by LegalEase - Draft for review",align="C")

def format_pdf(text, doc_type):
    pdf=LegalPDF(); pdf.set_auto_page_break(auto=True,margin=18); pdf.add_page()
    pdf.set_font("Helvetica","B",16); pdf.cell(0,10,sanitize_text(doc_type).upper(),ln=True,align="C"); pdf.ln(5)
    for line in sanitize_text(text).splitlines():
        line=line.strip()
        if not line: pdf.ln(3); continue
        pdf.set_font("Helvetica","B" if ((line.isupper() and len(line)<100) or line.endswith(":")) else "", 10.5)
        pdf.multi_cell(0,6,line); pdf.ln(1)
    return bytes(pdf.output())
